[project]
name = "streamlit-sample"
version = "1.0.0"
description = "Sample Streamlit application"
dependencies = [
    "streamlit==1.28.2",
    "pandas==2.1.4",
    "numpy==1.24.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []