apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

namePrefix: fastapi1-

patches:
  - path: app-port-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - APP_NAME=fastapi1
      - HOSTNAME=fastapi1.yu-min.k8s.local
      - OAUTH2_PROXY_CLIENT_ID=fastapi1
      - OAUTH2_PROXY_REDIRECT_URL=https://fastapi1.yu-min.k8s.local/oauth2/callback
      - OAUTH2_PROXY_UPSTREAM=http://fastapi1-app-service.default.svc.cluster.local:80
      - OAUTH2_PROXY_COOKIE_NAME=_oauth2_fastapi1_app
      - OAUTH2_PROXY_COOKIE_DOMAIN=fastapi1.yu-min.k8s.local
      # Replacement用の値
      - APP_SELECTOR=fastapi1
      - OAUTH2_SELECTOR=fastapi1-oauth2-proxy
      - APP_IMAGE=registry.yu-min.k8s.local/fastapi1:latest
      - OAUTH2_SERVICE_NAME=fastapi1-oauth2-proxy-service  # 追加

secretGenerator:
  - name: oauth2-proxy-secret
    envs:
      - secrets.env  # 環境変数ファイル参照

# 全ての PLACEHOLDER を置換
replacements:
  # HTTPRoute のホスト名を置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: HTTPRoute
          name: app-route
        fieldPaths:
          - spec.hostnames.0

  # HTTPRoute の OAuth2プロキシ backendRefs を置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.OAUTH2_SERVICE_NAME
    targets:
      - select:
          kind: HTTPRoute
          name: app-route
        fieldPaths:
          - spec.rules.0.backendRefs.0.name  # /oauth2/ path
          - spec.rules.1.backendRefs.0.name  # / path

  # アプリケーション Deployment のセレクターとラベルを置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.APP_SELECTOR
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app

  # アプリケーション Deployment のイメージを置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.APP_IMAGE
    targets:
      - select:
          kind: Deployment
          name: app
        fieldPaths:
          - spec.template.spec.containers.0.image


  # アプリケーション Service のセレクターを置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.APP_SELECTOR
    targets:
      - select:
          kind: Service
          name: app-service
        fieldPaths:
          - spec.selector.app

  # OAuth2プロキシ Deployment のセレクターとラベルを置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.OAUTH2_SELECTOR
    targets:
      - select:
          kind: Deployment
          name: oauth2-proxy
        fieldPaths:
          - spec.selector.matchLabels.app
          - spec.template.metadata.labels.app

  # OAuth2プロキシ Service のセレクターを置換
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.OAUTH2_SELECTOR
    targets:
      - select:
          kind: Service
          name: oauth2-proxy-service
        fieldPaths:
          - spec.selector.app

labels:
  - pairs:
      app.kubernetes.io/name: fastapi1
      app.kubernetes.io/component: web-app
      app.kubernetes.io/part-of: fastapi-platform

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"