apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamlit-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://your-git-repo.com/streamlit-apps.git
    targetRevision: HEAD
    path: argocd/streamlit-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true