apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: registry.yu-min.k8s.local/streamlit:latest
        ports:
        - containerPort: 8501  # Streamlitポート
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8501  # Streamlitポート