apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

namePrefix: streamlit1-

# パッチでHTTPRouteのbackendRefsを上書き
patchesStrategicMerge:
  - httproute-patch.yaml
  - app-streamlit-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - APP_NAME=streamlit1
      - HOSTNAME=streamlit1.yu-min.k8s.local
      - OAUTH2_PROXY_CLIENT_ID=streamlit1
      - OAUTH2_PROXY_REDIRECT_URL=https://streamlit1.yu-min.k8s.local/oauth2/callback
      - OAUTH2_PROXY_UPSTREAM=http://streamlit1-app-service.default.svc.cluster.local:80
      - OAUTH2_PROXY_COOKIE_NAME=_oauth2_streamlit1_app
      - OAUTH2_PROXY_COOKIE_DOMAIN=streamlit1.yu-min.k8s.local

secretGenerator:
  - name: oauth2-proxy-secret
    literals:
      - client-secret=OiezVYqIqI1WzYEZq2SGxO15FIqGcbhK
      - cookie-secret=eb7927d501b8b10e290a6d593a997e89

# ホスト名のみ置換（backendRefsはpatchで処理）
replacements:
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.HOSTNAME
    targets:
      - select:
          kind: HTTPRoute
          name: app-route
        fieldPaths:
          - spec.hostnames.0

images:
  - name: registry.yu-min.k8s.io/streamlit
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: streamlit1
      app.kubernetes.io/component: web-app
      app.kubernetes.io/part-of: streamlit-platform

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"