apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-secret
  namespace: default
spec:
  encryptedData:
    client-secret: AgAh6I2wLdZ786clabQ32WpnsH4ZidMUgcSxqNFnxCTu7asU0vUA3h2vwvOPfmd5rF0Zy3qqlQV6kkgFvYZD3JJocKg0xwcHYcDJQi00PDeKEkSLH467ssG1LTirGqUBDTRbcH++KEvjZwmKi3UIBcilces5fcrYvNtQ8thJt7LXSJucN6zzZlYRpd+7zog6KJYAJy/pvqsjzCrJrJ/5cljpGbUYufxZ7AP7JdY13E6i/TFQDQk4YTnigejluOECkkLE2o8ncbP315SQ5fhFEe4RHqBYcX3Sr8CHP3VozrzR3be0BQ1xN7OZDbTwe/hCH3j5DK/joyy4ABhG05pxWD9qunSyjO6UnXt04613gqEZBaqTqMZ2C7VNKvRZ/fEZfu+QzL/aS4NquwmiUGJXGvglGiPPSz5koo+J4D8Kj7g9cTmhUBBvZ1dDDrRyBNcdHMRK0ZF15jOa808W328aoIEnFtVCQ3TKs2Qa67MY6gNU/yxhTVvj5LlVwVvpC+jevS9AqCqu2UDJD5lMd5A8VLFguxLW2Cj33yqXPED5jDJW3URhEvWMWYkM30vc1VGBDXhZCqlr4srVdLCgEE9ZNIU/qrTzA9MXUT0P+H0XitAYU0jelDG/fefBeZZbjtRM7K6EWomt1z7FL8PRVjq5f3QCBhis6UGxtkHCRaWlFuEFn+RyPuGSdqZhelRQP4a4ROaDJ0K1CEgzfOVEBzX3DbD3uTEoJ3PZzOS+GnAxhZjiOg==
    cookie-secret: AgAiIdUxdP8dFXkKLMEHr+lloPzFWZiSsKxkjrfJv1lmeqYpwQeSRT+TjpUEQJGO5DSrl8Z8f0KxpM9b0/Z008N0tZapWS59yycAqJ+LUUYS8mQWjg9ejkXflI6OKdZGFltQUerZwjt2MaKLorHPhXszzNnGJHbQSofq9d9zgX6jJBgY5iDqYk9C8WdjtRKwBvmagtkh4WADJ0jy5n4GAns6Z4sWaErfRnu6NPZBYG6aWdlIsd6/AqAWjcKVnJygE32L/r+eGg4Hlze+XVtSehNvsqyIg6ytDZb2ogZCUdssWgTvPdMY6uuC52UXK5sXzxT6Sw2QHScBDGF6Y5J+Zo1UBl5TLDxRzuhEwD7etmNBPgD6H0Vqmp/tAbcJj3ijXUmv79aXd6MqEN0qYDUVI6BldEshzZ+zvM2f9vRYAvu9eM56pRfxCbsQI7SW1wCW802nDnwSLW+7DKo0ToDUKr+642j60Guiwe0PADr7ea2jUJ9v0DdOtH6h7MTNQrm12MNhHD9iWuYNkx42nL1HB1Kwz97bOs9RG/ILIBZx0hQifHj8JrVbTxaXBk36H+8ox+NAXEjxZb5A8eE3n2fDHSBMhu6PBRh5mZRTNyqN4DMVfTBk7YmiCWl0NgG1T2LkeihOkvKkA1h2D6ag/H0afOjHs3CR3oBbAUhxgQ8WRtRJ8x2Eke0TLCGz6gaV4ommDnIuPkbXEbhI2noj/KsEdBM9bATDafSkNz33g6wO8B7aCg==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy-secret
      namespace: default
---
