apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/yu-min3/my_k8s
    targetRevision: HEAD
    path: k8s/overlays/fastapi1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: fastapi1-app-config-*
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: fastapi1-oauth2-proxy-secret-*
      jsonPointers:
        - /data