apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret-streamlit1
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret-streamlit1
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret-streamlit1
                  key: cookie-secret
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: http://streamlit.local/oauth2/callback
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://streamlit:8501
          envFrom:
            - configMapRef:
                name: oauth2-proxy-env-streamlit1  # ← これを再度書く
